-- MySQL Script generated by MySQL Workbench
-- Mon May 29 14:46:52 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema practica_3
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `practica_3` ;

-- -----------------------------------------------------
-- Schema practica_3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `practica_3` DEFAULT CHARACTER SET utf8 ;
USE `practica_3` ;

-- -----------------------------------------------------
-- Table `practica_3`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `practica_3`.`productos` ;

CREATE TABLE IF NOT EXISTS `practica_3`.`productos` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(255) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `precioVenta` DECIMAL(5,2) NOT NULL,
  `precioCompra` DECIMAL(5,2) NOT NULL,
  `existencia` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `practica_3`.`tipo_medida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `practica_3`.`tipo_medida` ;

CREATE TABLE IF NOT EXISTS `practica_3`.`tipo_medida` (
  `idtipo_medida` INT(10) NOT NULL AUTO_INCREMENT,
  `medida` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipo_medida`),
  UNIQUE INDEX `idtipo_medida_UNIQUE` (`idtipo_medida` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `practica_3`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `practica_3`.`producto` ;

CREATE TABLE IF NOT EXISTS `practica_3`.`producto` (
  `idproducto` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_producto` VARCHAR(60) NOT NULL,
  `precio` FLOAT NOT NULL,
  `stock` INT(11) NULL,
  `idtipo_medida` INT(10) NOT NULL,
  PRIMARY KEY (`idproducto`),
  UNIQUE INDEX `idproducto_UNIQUE` (`idproducto` ASC) VISIBLE,
  INDEX `idtipo_medida` (`idtipo_medida` ASC) INVISIBLE,
  CONSTRAINT `idtipo_medida`
    FOREIGN KEY (`idtipo_medida`)
    REFERENCES `practica_3`.`tipo_medida` (`idtipo_medida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `practica_3`.`proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `practica_3`.`proveedor` ;

CREATE TABLE IF NOT EXISTS `practica_3`.`proveedor` (
  `idproveedor` INT(10) NOT NULL AUTO_INCREMENT,
  `nombre_proveedor` VARCHAR(70) NOT NULL,
  `direccion_proveedor` VARCHAR(100) NULL,
  `telefono_proveedor` VARCHAR(18) NULL,
  `email_proveedor` VARCHAR(60) NULL,
  `pagina_web_proveedor` VARCHAR(80) NULL,
  `idproducto` INT(11) NOT NULL,
  PRIMARY KEY (`idproveedor`),
  UNIQUE INDEX `idproveedor_UNIQUE` (`idproveedor` ASC) VISIBLE,
  INDEX `idproducto` (`idproducto` ASC) INVISIBLE,
  CONSTRAINT `idproducto`
    FOREIGN KEY (`idproducto`)
    REFERENCES `practica_3`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `practica_3`.`ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `practica_3`.`ventas` ;

CREATE TABLE IF NOT EXISTS `practica_3`.`ventas` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `total` DECIMAL(7,2) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `practica_3`.`productos_vendidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `practica_3`.`productos_vendidos` ;

CREATE TABLE IF NOT EXISTS `practica_3`.`productos_vendidos` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `cantidad` BIGINT(20) NOT NULL,
  `id_ventas` BIGINT(20) NOT NULL,
  `id_productos` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `id_ventas` (`id_ventas` ASC) VISIBLE,
  INDEX `id_productos` (`id_productos` ASC) INVISIBLE,
  CONSTRAINT `id_ventas`
    FOREIGN KEY (`id_ventas`)
    REFERENCES `practica_3`.`ventas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_productos`
    FOREIGN KEY (`id_productos`)
    REFERENCES `practica_3`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
