-- MySQL Script generated by MySQL Workbench
-- Wed Jun 28 17:47:57 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- ADSO 2556678
-- Diego Bolaños, Juan D. Gutierrez, Juan D. Cobo, Manuel Camacho, Nicole Galindez, Angela Campos, 
--Jonatan Diaz, Rubén Velasco.

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema confiapp_v2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema confiapp_v2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `confiapp_v2` DEFAULT CHARACTER SET utf8 ;
USE `confiapp_v2` ;

-- -----------------------------------------------------
-- Table `confiapp_v2`.`tipo_de_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `confiapp_v2`.`tipo_de_documento` (
  `idtipo_de_documento` INT NOT NULL AUTO_INCREMENT,
  `tipo_documento` VARCHAR(20) NOT NULL,
  `descripcion_documento` VARCHAR(100) NULL,
  PRIMARY KEY (`idtipo_de_documento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `confiapp_v2`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `confiapp_v2`.`perfil` (
  `idperfil` INT NOT NULL AUTO_INCREMENT,
  `perfil` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idperfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `confiapp_v2`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `confiapp_v2`.`genero` (
  `idgenero` INT NOT NULL AUTO_INCREMENT,
  `genero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idgenero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `confiapp_v2`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `confiapp_v2`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `idperfil` INT NOT NULL,
  `idtipo_de_documento` INT NOT NULL,
  `genero_idgenero` INT NOT NULL,
  `foto_persona` BLOB NULL,
  `primer_nombre` VARCHAR(20) NOT NULL,
  `segundo_nombre` VARCHAR(20) NOT NULL,
  `primer_apellido` VARCHAR(20) NOT NULL,
  `segundo_apellido` VARCHAR(20) NOT NULL,
  `direccion_usuario` VARCHAR(50) NOT NULL,
  `email_usuario` VARCHAR(50) NOT NULL,
  `contraseña_usuario` VARCHAR(20) NOT NULL,
  `telefono_usuario` VARCHAR(20) NOT NULL,
  `telefono_alternativo` VARCHAR(20) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `informacion_adicional` TEXT(100) NULL,
  `rh_usuario` VARCHAR(10) NULL,
  `numero_documento` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_tipo_de_documento1_idx` (`idtipo_de_documento` ASC) VISIBLE,
  INDEX `fk_usuario_perfil1_idx` (`idperfil` ASC) VISIBLE,
  INDEX `fk_usuario_genero1_idx` (`genero_idgenero` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_tipo_de_documento1`
    FOREIGN KEY (`idtipo_de_documento`)
    REFERENCES `confiapp_v2`.`tipo_de_documento` (`idtipo_de_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_perfil1`
    FOREIGN KEY (`idperfil`)
    REFERENCES `confiapp_v2`.`perfil` (`idperfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_genero1`
    FOREIGN KEY (`genero_idgenero`)
    REFERENCES `confiapp_v2`.`genero` (`idgenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `confiapp_v2`.`alertas_avisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `confiapp_v2`.`alertas_avisos` (
  `idalertas_avisos` INT NOT NULL AUTO_INCREMENT,
  `tipo_alerta_aviso` ENUM('Alerta', 'Aviso') NOT NULL,
  `ultima_ubicacion` POINT NOT NULL,
  `mensaje_alerta_aviso` VARCHAR(200) NOT NULL,
  `voz_alerta_aviso` BLOB NOT NULL,
  PRIMARY KEY (`idalertas_avisos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `confiapp_v2`.`ruta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `confiapp_v2`.`ruta` (
  `idruta` INT NOT NULL AUTO_INCREMENT,
  `idusuario` INT NOT NULL,
  `fecha_ruta` DATETIME NOT NULL,
  `punto_salida` VARCHAR(40) NOT NULL,
  `geosalida` POINT NOT NULL,
  `punto_llegada` VARCHAR(40) NOT NULL,
  `geollegada` POINT NOT NULL,
  `tiempo_estimado` TIME NOT NULL,
  `estado` ENUM("1.activa", "2. inactiva") NOT NULL,
  PRIMARY KEY (`idruta`),
  INDEX `fk_ruta_usuario1_idx` (`idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_ruta_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `confiapp_v2`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `confiapp_v2`.`medio_transporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `confiapp_v2`.`medio_transporte` (
  `idtipo_transporte` INT NOT NULL AUTO_INCREMENT,
  `nombre_transporte` VARCHAR(50) NOT NULL,
  `descripcion_transporte` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idtipo_transporte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `confiapp_v2`.`ruta_activa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `confiapp_v2`.`ruta_activa` (
  `idruta_activa` INT NOT NULL AUTO_INCREMENT,
  `idusuario` INT NOT NULL,
  `idruta` INT NOT NULL,
  `idtipo_transporte` INT NOT NULL,
  `fecha_actual` TIMESTAMP NOT NULL,
  `distancia_aproximada` FLOAT NOT NULL,
  `posicion_actual` POINT NOT NULL,
  PRIMARY KEY (`idruta_activa`),
  INDEX `fk_ruta_activa_ruta1_idx` (`idruta` ASC) VISIBLE,
  INDEX `fk_ruta_activa_medio_transporte1_idx` (`idtipo_transporte` ASC) VISIBLE,
  INDEX `fk_ruta_activa_usuario1_idx` (`idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_ruta_activa_ruta1`
    FOREIGN KEY (`idruta`)
    REFERENCES `confiapp_v2`.`ruta` (`idruta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ruta_activa_medio_transporte1`
    FOREIGN KEY (`idtipo_transporte`)
    REFERENCES `confiapp_v2`.`medio_transporte` (`idtipo_transporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ruta_activa_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `confiapp_v2`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `confiapp_v2`.`puntos_de_referencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `confiapp_v2`.`puntos_de_referencia` (
  `idpuntos_referencia` INT NOT NULL AUTO_INCREMENT,
  `nombre_punto` VARCHAR(50) NOT NULL,
  `direccion_punto` VARCHAR(50) NOT NULL,
  `georeferencia` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idpuntos_referencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `confiapp_v2`.`paradas_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `confiapp_v2`.`paradas_usuario` (
  `idpares_usuario` INT NOT NULL AUTO_INCREMENT,
  `fecha_parada` TIMESTAMP NOT NULL,
  `ubicacion_parada` POINT NOT NULL,
  `nombre_parada` VARCHAR(50) NOT NULL,
  `descripcion_parada` VARCHAR(225) NOT NULL,
  `actividad_parada` VARCHAR(100) NOT NULL,
  `duracion_parada` TIME NOT NULL,
  PRIMARY KEY (`idpares_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `confiapp_v2`.`puntosxruta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `confiapp_v2`.`puntosxruta` (
  `idpuntosxruta` INT NOT NULL AUTO_INCREMENT,
  `idruta` INT NOT NULL,
  `idpuntos_referencia` INT NOT NULL,
  PRIMARY KEY (`idpuntosxruta`),
  INDEX `fk_puntosxruta_ruta1_idx` (`idruta` ASC) VISIBLE,
  INDEX `fk_puntosxruta_puntos_de_referencia1_idx` (`idpuntos_referencia` ASC) VISIBLE,
  CONSTRAINT `fk_puntosxruta_ruta1`
    FOREIGN KEY (`idruta`)
    REFERENCES `confiapp_v2`.`ruta` (`idruta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_puntosxruta_puntos_de_referencia1`
    FOREIGN KEY (`idpuntos_referencia`)
    REFERENCES `confiapp_v2`.`puntos_de_referencia` (`idpuntos_referencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `confiapp_v2`.`rutaactivaxparadas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `confiapp_v2`.`rutaactivaxparadas` (
  `idrutaactivaxparadas` INT NOT NULL AUTO_INCREMENT,
  `idruta_activa` INT NOT NULL,
  `idpares_usuario` INT NOT NULL,
  PRIMARY KEY (`idrutaactivaxparadas`),
  INDEX `fk_rutaactivaxparadas_ruta_activa1_idx` (`idruta_activa` ASC) VISIBLE,
  INDEX `fk_rutaactivaxparadas_paradas_usuario1_idx` (`idpares_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_rutaactivaxparadas_ruta_activa1`
    FOREIGN KEY (`idruta_activa`)
    REFERENCES `confiapp_v2`.`ruta_activa` (`idruta_activa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rutaactivaxparadas_paradas_usuario1`
    FOREIGN KEY (`idpares_usuario`)
    REFERENCES `confiapp_v2`.`paradas_usuario` (`idpares_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `confiapp_v2`.`ractivaxalertas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `confiapp_v2`.`ractivaxalertas` (
  `idractivaxalertas` INT NOT NULL AUTO_INCREMENT,
  `idalertas_avisos` INT NOT NULL,
  `idruta_activa` INT NOT NULL,
  PRIMARY KEY (`idractivaxalertas`),
  INDEX `fk_ractivaxalertas_alertas_avisos1_idx` (`idalertas_avisos` ASC) VISIBLE,
  INDEX `fk_ractivaxalertas_ruta_activa1_idx` (`idruta_activa` ASC) VISIBLE,
  CONSTRAINT `fk_ractivaxalertas_alertas_avisos1`
    FOREIGN KEY (`idalertas_avisos`)
    REFERENCES `confiapp_v2`.`alertas_avisos` (`idalertas_avisos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ractivaxalertas_ruta_activa1`
    FOREIGN KEY (`idruta_activa`)
    REFERENCES `confiapp_v2`.`ruta_activa` (`idruta_activa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
