CREATE DATABASE Barcos;
USE Barcos;
CREATE TABLE Socios (
    ID INT NOT NULL AUTO_INCREMENT,
    Nombre VARCHAR(50) NOT NULL,
    Apellido VARCHAR(50) NOT NULL,
    DNI VARCHAR(10) NOT NULL,
    Direccion VARCHAR(100) NOT NULL,
    Telefono VARCHAR(20) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE Barcos (
    ID INT NOT NULL AUTO_INCREMENT,
    Matricula VARCHAR(10) NOT NULL,
    Nombre VARCHAR(50) NOT NULL,
    Amarre INT NOT NULL,
    Cuota FLOAT NOT NULL,
    SocioID INT NOT NULL,
    FOREIGN KEY (SocioID) REFERENCES Socios(ID),
    PRIMARY KEY (ID)
);

CREATE TABLE Salidas (
    ID INT NOT NULL AUTO_INCREMENT,
    FechaHora DATETIME NOT NULL,
    Destino VARCHAR(100) NOT NULL,
    PatronID INT NOT NULL,
    BarcoID INT NOT NULL,
    FOREIGN KEY (PatronID) REFERENCES Socios(ID),
    FOREIGN KEY (BarcoID) REFERENCES Barcos(ID),
    PRIMARY KEY (ID)
);
