-- MySQL Script generated by MySQL Workbench
-- Wed Apr 19 17:51:02 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Concesionario
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Concesionario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Concesionario` DEFAULT CHARACTER SET utf8 ;
USE `Concesionario` ;

-- -----------------------------------------------------
-- Table `Concesionario`.`auto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Concesionario`.`auto` (
  `idauto` INT NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `placa` VARCHAR(20) NOT NULL,
  `color` VARCHAR(20) NOT NULL,
  `cantidad_disponible` SMALLINT(2) NOT NULL,
  `estado_vehiculo` ENUM('nuevo', 'usado') NOT NULL,
  `kilometraje` SMALLINT(6) NOT NULL,
  PRIMARY KEY (`idauto`),
  UNIQUE INDEX `idauto_UNIQUE` (`idauto` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Concesionario`.`tipo_identificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Concesionario`.`tipo_identificacion` (
  `idtipo_identificacion` INT NOT NULL,
  `identificacion` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idtipo_identificacion`),
  UNIQUE INDEX `idtipo_identificacion_UNIQUE` (`idtipo_identificacion` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Concesionario`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Concesionario`.`cliente` (
  `idCliente` INT NOT NULL,
  `tipo_identificacion_idtipo_identificacion` INT NOT NULL,
  `identificacion` VARCHAR(20) NOT NULL,
  `nombre_cliente` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_cliente_tipo_identificacion_idx` (`tipo_identificacion_idtipo_identificacion` ASC) VISIBLE,
  UNIQUE INDEX `idCliente_UNIQUE` (`idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_tipo_identificacion`
    FOREIGN KEY (`tipo_identificacion_idtipo_identificacion`)
    REFERENCES `Concesionario`.`tipo_identificacion` (`idtipo_identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Concesionario`.`venta_vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Concesionario`.`venta_vehiculo` (
  `idventa_vehiculo` INT NOT NULL,
  `auto_idauto` INT NOT NULL,
  `cliente_idCliente` INT NOT NULL,
  `cantidad` VARCHAR(45) NOT NULL,
  `valor_unitario` FLOAT NOT NULL,
  `valor_total` FLOAT NOT NULL,
  `total_factura` FLOAT NOT NULL,
  PRIMARY KEY (`idventa_vehiculo`),
  INDEX `fk_venta_vehiculo_auto1_idx` (`auto_idauto` ASC) VISIBLE,
  INDEX `fk_venta_vehiculo_cliente1_idx` (`cliente_idCliente` ASC) VISIBLE,
  UNIQUE INDEX `idventa_vehiculo_UNIQUE` (`idventa_vehiculo` ASC) VISIBLE,
  CONSTRAINT `fk_venta_vehiculo_auto1`
    FOREIGN KEY (`auto_idauto`)
    REFERENCES `Concesionario`.`auto` (`idauto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_vehiculo_cliente1`
    FOREIGN KEY (`cliente_idCliente`)
    REFERENCES `Concesionario`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Concesionario`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Concesionario`.`venta` (
  `idVenta` INT NOT NULL,
  `fecha_venta` VARCHAR(45) NOT NULL,
  `venta_vehiculo_idventa_vehiculo` INT NOT NULL,
  PRIMARY KEY (`idVenta`),
  INDEX `fk_venta_venta_vehiculo1_idx` (`venta_vehiculo_idventa_vehiculo` ASC) VISIBLE,
  UNIQUE INDEX `idVenta_UNIQUE` (`idVenta` ASC) VISIBLE,
  CONSTRAINT `fk_venta_venta_vehiculo1`
    FOREIGN KEY (`venta_vehiculo_idventa_vehiculo`)
    REFERENCES `Concesionario`.`venta_vehiculo` (`idventa_vehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Concesionario`.`reparacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Concesionario`.`reparacion` (
  `idreparacion` INT NOT NULL,
  `auto_idauto` INT NOT NULL,
  `fecha_reparacion` VARCHAR(45) NOT NULL,
  `tiempo_estimado` TIME NOT NULL,
  PRIMARY KEY (`idreparacion`),
  INDEX `fk_reparacion_auto1_idx` (`auto_idauto` ASC) VISIBLE,
  UNIQUE INDEX `idreparacion_UNIQUE` (`idreparacion` ASC) VISIBLE,
  CONSTRAINT `fk_reparacion_auto1`
    FOREIGN KEY (`auto_idauto`)
    REFERENCES `Concesionario`.`auto` (`idauto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Concesionario`.`mecanico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Concesionario`.`mecanico` (
  `idmecanico` INT NOT NULL,
  `tipo_identificacion_idtipo_identificacion` INT NOT NULL,
  `nombre_mecanico` VARCHAR(45) NOT NULL,
  `apellido_mecanico` VARCHAR(45) NOT NULL,
  `identificacion` VARCHAR(15) NOT NULL,
  `salario` FLOAT NOT NULL,
  `fecha_contratacion` DATE NOT NULL,
  PRIMARY KEY (`idmecanico`),
  INDEX `fk_mecanico_tipo_identificacion1_idx` (`tipo_identificacion_idtipo_identificacion` ASC) VISIBLE,
  UNIQUE INDEX `idmecanico_UNIQUE` (`idmecanico` ASC) VISIBLE,
  CONSTRAINT `fk_mecanico_tipo_identificacion1`
    FOREIGN KEY (`tipo_identificacion_idtipo_identificacion`)
    REFERENCES `Concesionario`.`tipo_identificacion` (`idtipo_identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Concesionario`.`reparacion_has_mecanico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Concesionario`.`reparacion_has_mecanico` (
  `idreparacion_has_mecanico` INT NOT NULL,
  `reparacion_idreparacion` INT NOT NULL,
  `mecanico_idmecanico` INT NOT NULL,
  INDEX `fk_reparacion_has_mecanico_mecanico1_idx` (`mecanico_idmecanico` ASC) VISIBLE,
  INDEX `fk_reparacion_has_mecanico_reparacion1_idx` (`reparacion_idreparacion` ASC) VISIBLE,
  PRIMARY KEY (`idreparacion_has_mecanico`),
  UNIQUE INDEX `idreparacion_has_mecanico_UNIQUE` (`idreparacion_has_mecanico` ASC) VISIBLE,
  CONSTRAINT `fk_reparacion_has_mecanico_reparacion1`
    FOREIGN KEY (`reparacion_idreparacion`)
    REFERENCES `Concesionario`.`reparacion` (`idreparacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reparacion_has_mecanico_mecanico1`
    FOREIGN KEY (`mecanico_idmecanico`)
    REFERENCES `Concesionario`.`mecanico` (`idmecanico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
